version: '3.6'
services:

  postgres:
    image: mdillon/postgis
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  graphile:
    image: graphile/postgraphile
    ports:
      - "5000:5000"
    command: cli.js --connection postgres://postgres:@postgres:5432/postgres
      --watch --enhance-graphiql  --simple-collections only
      --schema asbestdaken,example,reclame,sportparken
      --skip-plugins graphile-build:NodePlugin
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/postgres

  # graphql-engine:
  #   image: hasura/graphql-engine:v1.0.0-beta.6
  #   ports:
  #   - "8088:8080"
  #   depends_on:
  #   - "postgres"
  #   restart: always
  #   environment:
  #     HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
  #     HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
  #     HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  #     ## uncomment next line to set an admin secret
  #     # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  nodejs:
    build: ./importer
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
      - WORKER_URL=http://worker/mapfiles
      - DATA_DIRECTORY=/data
      - MAPFILE_DIRECTORY=/mapfiles
    command:
      node server.js
    volumes:
      - ./data:/data
      - ./mapserver:/mapfiles

  worker:
    build: ./worker
    environment:
      FLASK_APP: web.py
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      SCHEMA_URL: https://schemas.data.amsterdam.nl/datasets/
      UWSGI_DIE_ON_TERM: "1"
      UWSGI_HARAKIRI: "25"
      UWSGI_HTTP: ":8080"
      UWSGI_MASTER: "1"
      UWSGI_MODULE: "dynapi.wsgi:application"
      UWSGI_OFFLOAD_THREADS: "3"
      UWSGI_PROCESSES: "4"
      UWSGI_STATIC_MAP: "/static=/static"
      UWSGI_VACUUM: "1"
    extra_hosts: 
      - "schemas.data.amsterdam.nl:194.104.80.4"
    ports:
      - "7080:8080"
        #    command:
        # bash run.sh
      # sleep infinity
      # uwsgi -w worker.web:app

  mapserver:
    build: ./mapserver
    volumes:
      - ./mapserver:/srv/mapserver

  dynapi:
    build: ./dynapi
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      SCHEMA_URL: https://schemas.data.amsterdam.nl/datasets/
      ROUTES_ROOT_DIR: /data
      URI_PATH_PREFIX: /api/
      UWSGI_DIE_ON_TERM: "1"
      UWSGI_HARAKIRI: "25"
      UWSGI_HTTP: ":8080"
      UWSGI_MASTER: "1"
      UWSGI_MODULE: "dynapi.wsgi:application"
      UWSGI_OFFLOAD_THREADS: "3"
      UWSGI_PROCESSES: "4"
      UWSGI_STATIC_MAP: "/static=/static"
      UWSGI_VACUUM: "1"
        #    command:
        #sleep infinity
      #      gunicorn dynapi.wsgi:application -w 1 -b 0.0.0.0:9080
    extra_hosts: 
      - "schemas.data.amsterdam.nl:194.104.80.4"
    volumes:
      - ./dynapi:/dynapi
      - ./data:/data
    ports:
      - "8080:8080"

  proxy:
    build: ./proxy
    ports:
      - "9080:80"

volumes:
  db_data:
