version: '3.6'
services:
  postgres:
    image: mdillon/postgis
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.6
    ports:
    - "8088:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  nodejs:
    image: node:12
    ports:
    - "8765:8080"
    environment:
    - PORT=8080
    - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
    - HASURA_URL=http://graphql-engine:8088/
    command: node /app/server.js
    volumes:
    - ./:/app
  worker:
    build: ./worker
    environment:
      FLASK_APP: web.py
    ports:
      - "5000:5000"

volumes:
  db_data:
